{{- $fullName := include "grease-monkey.fullname" . -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-{{ $fullName }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/tls-acme: 'true'
spec:
  tls:
  - hosts:
    - {{ template "grease-monkey.domain" . }}
    secretName: tls-secret-{{ $fullName }}
  rules:
  - host: {{ template "grease-monkey.domain" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ .Values.service.port }}