{{- $fullName := include "grease-monkey.fullname" . -}}

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ $fullName }}
spec:
  acme:
    # Email address used for cert registration
    email: {{ .Values.emailAddress | default "developers@schierproducts.com" | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-{{ $fullName }}-private-key
    solvers:
      - http01:
          ingress:
            class: nginx