apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grease-monkey.fullname" . }}
  labels:
    app: {{ template "grease-monkey.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.keepSecrets }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
type: Opaque
data:
  {{- if .Values.mysql.rootPassword }}
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  {{- if and .Values.mysql.user .Values.mysql.password }}
  mysql-user: {{ .Values.mysql.user | b64enc | quote }}
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
  {{- if .Values.mysql.database}}
  mysql-database: {{ .Values.mysql.database | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.filesystem.cloud }}
  filesystem-key: {{ .Values.filesystem.aws.key | b64enc | quote }}
  filesystem-access: {{ .Values.filesystem.aws.access | b64enc | quote }}
  filesystem-region: {{ .Values.filesystem.aws.region | b64enc | quote }}
  filesystem-bucket: {{ .Values.filesystem.aws.bucket | b64enc | quote }}
  {{- end }}
