apiVersion: v1
kind: Service
metadata:
  name: {{ include "grease-monkey.fullname" . }}
  namespace: default
  labels:
    app: {{ template "grease-monkey.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  externalName: {{ include "grease-monkey.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  ports:
    - name: {{ include "grease-monkey.fullname" . }}
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ template "grease-monkey.fullname" . }}
